name: flutter_milai
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_advanced_networkimage: ^0.3.13 #网络缓存图片库
  dio: ^1.0.9                           #http网络请求库
  common_utils: ^1.0.9                  #常用小工具集合
  json_annotation: ^2.0.0
  flutter_swiper: ^1.1.4                #轮播图
  pull_to_refresh: ^1.1.6               #下拉刷新上拉加载
  flutter_wechat: "^0.1.5"              #微信
  fluttertoast: ^2.1.5                  #toast
  shared_preferences: ^0.4.3
  crypto: ^2.0.6                        #支持SHA-1、SHA-256、MD5、HMAC
  encrypt: ^0.2.0+2
  event_bus: ^1.0.1
  image_picker: ^0.4.10
  image_cropper: ^0.0.9
  badge: ^0.0.3                         #角标


dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^2.0.0             #json解析库
  build_runner: ^1.1.2

flutter:
  uses-material-design: true

  assets:
   - images/no_picture.png
   - images/service_ico.png
   - images/trace_no_login.png
   - images/login_close_ico.png
   - images/logo.png
   - images/weixin_ico.png
   - images/open_eye_ico.png
   - images/close_eye_ico.png
   - images/trace_edit_ico.png
   - images/person_head_bg.png
   - images/person_setting_ico.png
   - images/person_chat_ico.png
   - images/person_order_1.png
   - images/person_order_2.png
   - images/person_order_3.png
   - images/person_order_4.png
   - images/person_order_5.png
   - images/person_head_ico.png
   - images/person_tuike_ico.png
   - images/person_tuike_code_ico.png
   - images/person_phone_ico.png
   - images/person_activity_1.png
   - images/person_activity_2.png
   - images/person_activity_3.png
   - images/person_activity_4.png
   - images/person_activity_5.png
   - images/person_tool_1.png
   - images/person_tool_2.png
   - images/person_tool_3.png
   - images/person_tool_4.png
   - images/person_tool_5.png
   - images/person_applying_ad.png
   - images/person_pull_friend_ad.png
   - images/person_to_apply_ad.png
   - images/person_join_ad.png
   - images/service_dialog_bg.png
   - images/service_dialog_title.png