name: flutter_milai
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  cached_network_image: ^0.5.1          #网络缓存图片库
  dio: ^1.0.9                           #http网络请求库
  common_utils: ^1.0.9                  #常用小工具集合
  json_annotation: ^2.0.0
  flutter_swiper: ^1.1.4                #轮播图
  pull_to_refresh: ^1.1.6               #下拉刷新上拉加载
  flutter_wechat: "^0.1.5"              #微信
  fluttertoast: ^2.1.5                  #toast
  shared_preferences: ^0.4.3
  crypto: ^2.0.6                        #支持SHA-1、SHA-256、MD5、HMAC
  encrypt: ^0.2.0+2
  device_info: ^0.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^2.0.0             #json解析库
  build_runner: ^1.1.2

flutter:
  uses-material-design: true

  assets:
   - images/no_picture.png
   - images/service_ico.png
   - images/trace_no_login.png
   - images/login_close_ico.png
   - images/logo.png
   - images/weixin_ico.png
   - images/open_eye_ico.png
   - images/close_eye_ico.png