// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

UserModel _$UserModelFromJson(Map<String, dynamic> json) {
  return UserModel(
      json['LastLoginTime'] as String,
      json['IsDistributorApply'] as String,
      json['IsDistributor'] as String,
      json['PushID'] as String,
      json['Address'] as String,
      json['WeiXinUnionId'] as String,
      json['WeiXinOpenId'] as String,
      json['Email'] as String,
      json['HeadImageUrl'] as String,
      json['Account'] as String,
      json['WeiXinNickName'] as String,
      json['ProvinceCode'] as String,
      json['Sex'] as String,
      json['QQ'] as String,
      json['Integral'] as String,
      json['CityCode'] as String,
      json['IsSubscribe'] as String,
      json['SexName'] as String,
      json['TerminalType'] as String,
      json['Lng'] as String,
      json['Mobile'] as String,
      json['AliPay'] as String,
      json['AreaCode'] as String,
      json['ID'] as String,
      json['Lat'] as String,
      json['WeiXin'] as String,
      json['StreetCode'] as String,
      json['MiLaiMoney'] as String,
      json['WeiXinTXOpenId'] as String,
      json['Birthday'] as String,
      json['IsNewUser'] as String,
      json['NickName'] as String,
      json['RealName'] as String,
      json['WeiXinPCOpenId'] as String,
      json['Level'] as String,
      json['IsPush'] as String,
      json['IsVerificationEmail'] as String,
      json['IsVerificationMobile'] as String);
}

Map<String, dynamic> _$UserModelToJson(UserModel instance) => <String, dynamic>{
      'LastLoginTime': instance.lastLoginTime,
      'IsDistributorApply': instance.isDistributorApply,
      'IsDistributor': instance.isDistributor,
      'PushID': instance.pushID,
      'Address': instance.address,
      'WeiXinUnionId': instance.weiXinUnionId,
      'WeiXinOpenId': instance.weiXinOpenId,
      'Email': instance.email,
      'HeadImageUrl': instance.headImageUrl,
      'Account': instance.account,
      'WeiXinNickName': instance.weiXinNickName,
      'ProvinceCode': instance.provinceCode,
      'Sex': instance.sex,
      'QQ': instance.qQ,
      'Integral': instance.integral,
      'CityCode': instance.cityCode,
      'IsSubscribe': instance.isSubscribe,
      'SexName': instance.sexName,
      'TerminalType': instance.terminalType,
      'Lng': instance.lng,
      'Mobile': instance.mobile,
      'AliPay': instance.aliPay,
      'AreaCode': instance.areaCode,
      'ID': instance.iD,
      'Lat': instance.lat,
      'WeiXin': instance.weiXin,
      'StreetCode': instance.streetCode,
      'MiLaiMoney': instance.miLaiMoney,
      'WeiXinTXOpenId': instance.weiXinTXOpenId,
      'Birthday': instance.birthday,
      'IsNewUser': instance.isNewUser,
      'NickName': instance.nickName,
      'RealName': instance.realName,
      'WeiXinPCOpenId': instance.weiXinPCOpenId,
      'Level': instance.level,
      'IsPush': instance.isPush,
      'IsVerificationEmail': instance.isVerificationEmail,
      'IsVerificationMobile': instance.isVerificationMobile
    };
